### ISSUE TITLE
好手氣

### ISSUE THREAD

**Issue by ksc91u** [cornguo/cornguo.github.io#1]
如果唱歌唱到一半按好手氣的話, 會壞掉, 沒辦法放下一首。

**Comment by cornguo** [comment]
請問執行的環境是？

**Comment by ksc91u** [comment]
Google Chrome
Version 32.0.1700.68 beta

OS X 10.9

**Comment by cornguo** [comment]
有借了朋友的 Mac 測試，但無法重製，這幾天會再看看是不是有其他可能的問題，感謝回報 : )

**Comment by cornguo** [comment]
今天在自己的 PC 上面遇到了類似的錯誤，也已經放了修正上去，
不確定是否能修正問題，但錯誤應該會減少一些
